language: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.3.1
services:
- docker
before_install:
- docker pull mumuki/mumuki-junit-worker
- wget https://github.com/mumuki/mulang/releases/download/v2.0.0/mulang
- mv mulang bin/
- chmod +x bin/mulang
deploy:
  provider: rubygems
  api_key:
    secure: OgB9WDBvjGguaobK6H+gko7uny+zZLKW++6fqdYd9Tz+ARecpFqfw3PcMXEqrLVmU7f/HXKpWXp85KP2ZUUXzkHpDdjdLeaGgdVmPsFO4+CepJ8qkyu1B/PqBFI/WmGUDLMYIc5fHohb7exXH2lVpuHfwwD+Y46C8ZYiwktMNGq09uiiDfOHB8r9oBl7v0WaO+bHuHpYnKLuoTzBml1TgdoOR8auqkz5Nld+R2DTANvKt8gFngaHf6sFxVfd9N+JfIDYMwjnP0RifnuZ6+dOsjmfpTvMcuejRxmqVrHuBWa69yVq+pRn4bjXwz1wXQpgGTpcWGTuy7Hb6bic3Iftqte/kAFfPk6tM97iSBut9uh+CXgBgCr8buqdTRJk/0eMHl98fW+SztkgretHRG+Sx9lvEOf+rNnFxngdYlFk4Bta/YWN4e7Dt7UK8NxLO36v7lQ73JMFQXO9h1AxroOTMRnn/zBKEjxAqEpGc8iQCadOtajhbHw2LXKfw/DJYn3nQk1dQYtVavf7Ui6OaCA0d9XPVYIi/903GXlu/YfAkSaHZJwEd8VWc/khqIgAd1i71Uy2Iy7fbozBAu2PKZvzM5/f269UMVJrltllcH8gzRZeC32Bx0Smw1b8zMr3xRJRca3lVT/1dCWoVMUbTv2W5wIkV8Mslq6BE9e/OXbSnbw=
  gem: mumuki-java-runner
  on:
    tags: true
    repo: mumuki/mumuki-java-runner
