#!/bin/bash
directory=$(mktemp -d)
cp $1 $directory/Query.java
javac "$directory/Query.java" 2>&1

if [ $? -ne 0 ] ; then
  echo "!!SUBMISSION FINISHED WITH COMPILATION ERROR!!"
  exit 1
fi

java -cp "$CLASSPATH:$directory" Query
exit $?
